### ISSUE TITLE
Commands are not received after about 1 hour of running my telegram bot

### ISSUE THREAD

**Issue by moobid** [kotlin-telegram-bot/kotlin-telegram-bot#211]
**Expected behavior**
Commands that the user sends are received reliably in the telegram bot

**Actual behavior**
After about 1 hour of run time of my telegram bot newly sent commands dont "arrive" in the application. In the time from start up until about 1 hour the commands "arrive" reliably.
After a restart of my telegram bot the stuck commands are processed directly at startup.
Also, the bot sends a message like every 10 seconds, which works fine.
I noticed this behaviour for about 5 days now and I did not update anything.

**To Reproduce**
Hard to reproduce. Currently I am running the application directly with IntelliJ.

**Screenshots/Traceback**
No exceptions occur / are visible. Is there a way to see a log of my telegram bot from the Telegram's perspective?

**Possible solutions**
-

**Additional context**
-

**Comment by aivel** [comment]
Hi there!

I am having the same issue
I use long polling for updates retrieval

@moobid are you using long polling as well or this problem is also reproducible with webhooks?

**Comment by moobid** [comment]
Hi @aivel,
I am also using polling.
The issue still persists. Currently I am running my application on my raspberry pi and scheduled the application to restart every 30minutes to prevent this issue. But this is quite annoying...
Help or ideas are much appreciated

**Comment by ivanantipin** [comment]
same here, i see that 2 threads dies when it happens ( suppose some unhandled exception)


"OkHttp api.telegram.org" #36 prio=5 os_prio=0 cpu=166.03ms elapsed=1148.08s tid=0x00007f44bc2fa000 nid=0x36 runnable  [0x00007f4498af5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.poll(java.base@13.0.2/Native Method)
	at sun.nio.ch.NioSocketImpl.park(java.base@13.0.2/NioSocketImpl.java:182)
	at sun.nio.ch.NioSocketImpl.park(java.base@13.0.2/NioSocketImpl.java:191)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@13.0.2/NioSocketImpl.java:315)
	at sun.nio.ch.NioSocketImpl.read(java.base@13.0.2/NioSocketImpl.java:351)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@13.0.2/NioSocketImpl.java:802)
	at java.net.Socket$SocketInputStream.read(java.base@13.0.2/Socket.java:937)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@13.0.2/SSLSocketInputRecord.java:450)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@13.0.2/SSLSocketInputRecord.java:68)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@13.0.2/SSLSocketImpl.java:1409)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@13.0.2/SSLSocketImpl.java:1022)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:67)
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:95)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:566)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.lang.Thread.run(java.base@13.0.2/Thread.java:830)

"Okio Watchdog" #38 daemon prio=5 os_prio=0 cpu=6.97ms elapsed=1148.03s tid=0x00007f44bc320000 nid=0x38 in Object.wait()  [0x00007f449869f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@13.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@13.0.2/Object.java:460)
	at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:361)
	at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:312)
	- locked <0x00000000c4ba4668> (a java.lang.Class for okio.AsyncTimeout)

**Comment by ForegroundGravity** [comment]
I have a similar issue. my bot **stops** sending GET requests after some time. but POST requests continue to work

and I cannot find any exception in the logs. tried everything already :(

**Comment by PicoPocoo** [comment]
same Issue here, did anyone find a workaround? Periodically restarting the bot?

**Comment by moobid** [comment]
> same Issue here, did anyone find a workaround? Periodically restarting the bot?

I am periodically (every 30min) restarting my application. But this is annoying

**Comment by ForegroundGravity** [comment]
As a workaround, I tried to set a timer inside my bot to restart polling every hour. I stop polling and then start it again in a minute. It helps to limit downtime within one hour. But still the polling can stuck even after several minutes after start :(

I've been using this wrapper almost for a year now, but started to experience this bug only recently. 

@seik , @vjgarciag96 Dear Sirs, could you, please, take a look at this issue? It looks critical.

**Comment by vjgarciag96** [comment]
There's an option to see any exceptions happening in the execution of commands, by adding the next line in the bot set up:

```kotlin
bot {
    logLevel = LogLevel.All()
}
```

There's some doc here with more details about logging https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/blob/main/docs/logging.md

At the moment, the info we have is:

* It happens, at least, from v6.0.0, as @ForegroundGravity reported.
* The thread dump of the threads that seem to die that @ivanantipin sent (which I can't get much ideas from).

I'll try to reproduce this locally and see if I can find the cause of the issue. 

In the meantime, it could be helpful if some of the reporters add some extra information so we can get a better understanding of the issue. Some information that could be helpful:

1. What version of the library are you using?
2. What configuration do you have for the bot? Basically the main block where you declare the bot, the commands and other things.

I'll keep you posted with any findings.

**Comment by ivanantipin** [comment]
apparently okhttp threads dies silently - because i do not see any errors in unhandled exceptions handler registered for jvm

**Comment by moobid** [comment]
I am using 6.0.4.
I was using this bot from the start of June. The issue first occured to me mid June.
My configuration is quite simple:
`
[...]
override val bot = bot {
        token = "<mytoken>"
        timeout = 20
        logLevel = LogLevel.Error

        dispatch {
            command("continue") {
                 [...]
            }
            [... about 8 more commands ...]
       }
       [...]
}

`

**Comment by madsunrise** [comment]
I have the same issue (Spring + Tomcat), bot just stops sending GET-requests to api.telegram.org after a while. Version 6.0.4.

**Comment by Lood** [comment]
I replaced the retrofit and converter-gson to newer versions. 
```
implementation("io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram:6.0.4"){
        exclude("com.squareup.retrofit2","retrofit")
        exclude("com.squareup.retrofit2","converter-gson")
        implementation("com.squareup.retrofit2:retrofit:2.9.0")
        implementation("com.squareup.retrofit2:converter-gson:2.9.0")
    }
```
After that, the bot works for a week without failures.

**Comment by moobid** [comment]
@Lood, thanks for sharing. Can confirm that it works: my telegram bot now runs for 1:50 h and still responds to commands.

**Comment by vjgarciag96** [comment]
Nice one @Lood! I'll bump the library versions and publish a new library artifact with the update 👍🏻

**Comment by vjgarciag96** [comment]
A new version of the library (6.0.5) has been published with the change proposed by @Lood included in it. @moobid @Lood @madsunrise @ivanantipin @ForegroundGravity @PicoPocoo @aivel please let me know if you can still reproduce the issue with this new version.

**Comment by ForegroundGravity** [comment]
Seems to work fine now. Thank you all, guys!

**Comment by madsunrise** [comment]
Confirmed one week of continuous work without any problems. @vjgarciag96, @Lood appreciate.
