### ISSUE TITLE
Okhttp version is too old.

### ISSUE THREAD

**Issue by TigerBeanst** [kotlin-telegram-bot/kotlin-telegram-bot#271]
Trying to print Log:
```kotlin
val bot = bot {
        ...
        logLevel = LogLevel.All()
    }
```

But:
```
Exception in thread "pool-1-thread-2" java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)'
	at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:111)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:159)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at com.github.kotlintelegrambot.network.ApiRequestSender.send(ApiRequestSender.kt:7)
	at com.github.kotlintelegrambot.network.ApiClient.runApiOperation(ApiClient.kt:1329)
	at com.github.kotlintelegrambot.network.ApiClient.getUpdates(ApiClient.kt:120)
	at com.github.kotlintelegrambot.updater.Updater$startPolling$1.invoke(Updater.kt:21)
	at com.github.kotlintelegrambot.updater.Updater$startPolling$1.invoke(Updater.kt:20)
	at com.github.kotlintelegrambot.updater.ExecutorLooper.runLoop(Looper.kt:28)
	at com.github.kotlintelegrambot.updater.ExecutorLooper.loop$lambda-0(Looper.kt:23)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Then I found that kotlin-telegram-bot depends on okhttp 3.14.9
![image](https://user-images.githubusercontent.com/3889846/199899667-793da1f9-81ed-472b-8560-bdd4e6a00f43.png)

And ktor depends on 4.9.3....

**Comment by Rattlyy** [comment]
bump?

**Comment by red-avtovo** [comment]
@TigerBeanst @Rattlyy would be great if you could raise a PR

**Comment by Rattlyy** [comment]
@red-avtovo I'll do so in ~8hrs. Sorry if I passed off as rude :)

**Comment by iakunin** [comment]
@red-avtovo hello! Could you take a look at #346, please?

**Comment by seik** [comment]
Resolved by #346 (merged in commit bb56b57): okhttp3 has been bumped to 4.12.0 and the logging interceptor with it. Closing.
